# Generated by Django 5.1.6 on 2025-02-24 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default="This is the product's default description"),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
